---
name: Captcha
author: xiaochen
description: Captcha
topic: Captcha
algorithm: SENet
language: python3
virtualenv: flyai_env/bin/

framework: PyTorch

data:
  id: Captcha
  name: Captcha
  category: image


model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: img_path
        type: string
    to_type: float
    to_shape: [66,66,3]
  output:
    columns:
      - name: label
        type: int
    to_type: float
    to_shape: [-1,80]


evaluate:
  score: torch_accuracy

servers:
 - id: flyai
   url: https://flyai.com
...